### ISSUE TITLE
Autoban/warn on key words

### ISSUE THREAD

**Issue by glass-ships** [lu-ci/apex-sigma-core#186]
Would love to be able to configure sigma to automatically ban or mute users who use particular slurs. Possible with the current API?

**Comment by AXAz0r** [comment]
Sigma is currently in a feature freeze due to an upcoming rewrite. This is also just a mirror repository, the real one is on GL, the link is in this repo's desc.

**Comment by glass-ships** [comment]
Oh wow had no idea! Thanks for the update :)
